project:
  name: &projectName Exporter PSQL to Clickhouse PROD
  version: 1.0.0
  timeout: 9
  swagger_enabled: false
  max_body_mb: 20
  cache_timeout: 30
logging:
  projectName: *projectName
  code: zap
  encoding: json
  level: warning
  dateTimeFormat: 2006-01-02 15:04:05
  dateFormat: 2006-01-02
  enableCaller: true
  devMode: false
